function buildBatchImageOcrScript(options = {}) {
  const opts = (options && typeof options === 'object') ? options : {};
  const jobs = Array.isArray(opts.jobs) ? opts.jobs : [];
  const matchPattern = String(opts.matchPattern || '').trim();

  return [
    'import json',
    'import re',
    'import numpy as np',
    'from PIL import Image, ImageOps, ImageFilter',
    'from rapidocr_onnxruntime import RapidOCR',
    '',
    `JOBS = json.loads(${JSON.stringify(JSON.stringify(jobs))})`,
    `MATCH_PATTERN = ${JSON.stringify(matchPattern)}`,
    'FILENAME_PATTERN = re.compile(r"\\b(?=[A-Za-z0-9._-]{3,64}\\b)(?=.*[A-Za-z])(?=.*(?:\\d|[_-]))[A-Za-z0-9._-]+\\b")',
    '',
    'def _resample_lanczos():',
    '    image_mod = getattr(Image, "Resampling", None)',
    '    if image_mod is not None and hasattr(image_mod, "LANCZOS"):',
    '        return image_mod.LANCZOS',
    '    return getattr(Image, "LANCZOS", Image.BICUBIC)',
    '',
    'def _normalize_score(value):',
    '    try:',
    '        return float(value)',
    '    except Exception:',
    '        return 0.0',
    '',
    'def _dedupe_lines(lines):',
    '    out = []',
    '    seen = set()',
    '    for item in lines:',
    '        text = str((item or {}).get("text", "")).strip()',
    '        if not text:',
    '            continue',
    '        key = text.lower()',
    '        if key in seen:',
    '            continue',
    '        seen.add(key)',
    '        out.append({"text": text, "score": round(_normalize_score((item or {}).get("score", 0.0)), 4)})',
    '    return out',
    '',
    'def _lines_from_ocr(raw):',
    '    out = []',
    '    if not raw:',
    '        return out',
    '    for item in raw:',
    '        if isinstance(item, (list, tuple)) and len(item) >= 3:',
    '            out.append({"text": str(item[1] or "").strip(), "score": _normalize_score(item[2])})',
    '        elif isinstance(item, (list, tuple)) and len(item) >= 2:',
    '            out.append({"text": str(item[0] or "").strip(), "score": _normalize_score(item[1])})',
    '        else:',
    '            out.append({"text": str(item or "").strip(), "score": 0.0})',
    '    return _dedupe_lines(out)',
    '',
    'def _extract_matches(text, compiled_pattern=None):',
    '    source = str(text or "").strip()',
    '    explicit = []',
    '    if compiled_pattern is not None and source:',
    '        for match in compiled_pattern.findall(source):',
    '            if isinstance(match, tuple):',
    '                candidate = "".join(str(part or "") for part in match)',
    '            else:',
    '                candidate = str(match or "")',
    '            candidate = candidate.strip()',
    '            if candidate and candidate not in explicit:',
    '                explicit.append(candidate)',
    '    inferred = []',
    '    if source:',
    '        for match in FILENAME_PATTERN.findall(source):',
    '            candidate = str(match or "").strip()',
    '            if candidate and candidate not in inferred:',
    '                inferred.append(candidate)',
    '    return explicit, inferred',
    '',
    'def _variant_score(text, lines, explicit_matches):',
    '    text_value = str(text or "")',
    '    char_score = len(text_value)',
    '    confidence_score = int(sum(_normalize_score((item or {}).get("score", 0.0)) * 100 for item in lines))',
    '    explicit_bonus = len(explicit_matches) * 10000',
    '    return explicit_bonus + char_score + confidence_score',
    '',
    'def _build_variants(image):',
    '    resample = _resample_lanczos()',
    '    rgb = image.convert("RGB")',
    '    gray = ImageOps.autocontrast(ImageOps.grayscale(rgb))',
    '    sharp = gray.filter(ImageFilter.SHARPEN)',
    '    threshold = sharp.point(lambda px: 255 if px >= 160 else 0)',
    '    variants = [',
    '        ("original", np.array(rgb)),',
    '        ("gray_2x", np.array(gray.resize((max(1, gray.width * 2), max(1, gray.height * 2)), resample=resample))),',
    '        ("threshold_2x", np.array(threshold.resize((max(1, threshold.width * 2), max(1, threshold.height * 2)), resample=resample))),',
    '    ]',
    '    return variants',
    '',
    'def _ocr_one(engine, job, compiled_pattern=None):',
    '    path = str((job or {}).get("stored_path", "")).strip()',
    '    meta = {',
    '        "context_file_id": str((job or {}).get("context_file_id", "")).strip(),',
    '        "file_name": str((job or {}).get("file_name", "")).strip(),',
    '        "relative_path": str((job or {}).get("relative_path", "")).strip(),',
    '    }',
    '    if not path:',
    '        return {**meta, "ok": False, "error": "stored_path is required.", "text": "", "matches": [], "inferred_matches": [], "best_match": "", "lines": [], "variant_used": ""}',
    '    image = Image.open(path)',
    '    best = None',
    '    for variant_name, variant_img in _build_variants(image):',
    '        raw, _ = engine(variant_img)',
    '        lines = _lines_from_ocr(raw)',
    '        text = "\\n".join(item["text"] for item in lines if str((item or {}).get("text", "")).strip())',
    '        explicit_matches, inferred_matches = _extract_matches(text, compiled_pattern)',
    '        score = _variant_score(text, lines, explicit_matches)',
    '        candidate = {',
    '            **meta,',
    '            "ok": True,',
    '            "error": "",',
    '            "text": text,',
    '            "matches": explicit_matches,',
    '            "inferred_matches": inferred_matches,',
    '            "best_match": (explicit_matches[0] if explicit_matches else (inferred_matches[0] if inferred_matches else "")),',
    '            "lines": lines,',
    '            "variant_used": variant_name,',
    '            "_score": score,',
    '        }',
    '        if best is None or score > best["_score"]:',
    '            best = candidate',
    '    if best is None:',
    '        return {**meta, "ok": False, "error": "OCR returned no result.", "text": "", "matches": [], "inferred_matches": [], "best_match": "", "lines": [], "variant_used": ""}',
    '    best.pop("_score", None)',
    '    return best',
    '',
    'def main():',
    '    compiled_pattern = re.compile(MATCH_PATTERN) if MATCH_PATTERN else None',
    '    engine = RapidOCR()',
    '    results = []',
    '    for job in JOBS:',
    '        try:',
    '            results.append(_ocr_one(engine, job, compiled_pattern))',
    '        except Exception as err:',
    '            results.append({',
    '                "context_file_id": str((job or {}).get("context_file_id", "")).strip(),',
    '                "file_name": str((job or {}).get("file_name", "")).strip(),',
    '                "relative_path": str((job or {}).get("relative_path", "")).strip(),',
    '                "ok": False,',
    '                "error": str(err),',
    '                "text": "",',
    '                "matches": [],',
    '                "inferred_matches": [],',
    '                "best_match": "",',
    '                "lines": [],',
    '                "variant_used": "",',
    '            })',
    '    payload = {',
    '        "ok": True,',
    '        "engine": "rapidocr-onnxruntime",',
    '        "count": len(results),',
    '        "results": results,',
    '    }',
    '    print(json.dumps(payload, ensure_ascii=True))',
    '',
    'main()',
    '',
  ].join('\n');
}

function parseBatchImageOcrResult(stdout = '') {
  const text = String(stdout || '').trim();
  if (!text) return null;
  const lines = text.split(/\r?\n/).map((line) => line.trim()).filter(Boolean);
  for (let i = lines.length - 1; i >= 0; i -= 1) {
    try {
      return JSON.parse(lines[i]);
    } catch (_) {
      // Ignore non-JSON lines before the payload.
    }
  }
  return null;
}

module.exports = {
  buildBatchImageOcrScript,
  parseBatchImageOcrResult,
};
